# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R42eRJQt20uNKv0rwhK_eNXLXBVbzipv
"""

l=[1,2,3,4,5]
for i in l:
  print(i,type(i))

l1=["abhay","kumar","gautam","sunil","singh"]
for i in l1:
  print(i)

for i in l1 :
  print(i)
else:
  print("do something")

l1

for i in l1:
  if i =="gautam":
    break
  print(i)  
else:
  print("for loop apply")

l1

for i in l1:
  if i=="gautam":
    continue
  print(i) 
else:
  print("execute for loop")

for i in range(1,30,3):
  print(i)

range(5)

list(range(0,5))

list(range(0,20,2))

list(range(-10,0))

l1=["abhay","kumar","gautam","sunil","singh"]

len(l1)

range(len(l1))

list(range(len(l1)))

for i in range(len(l1)):
  print(l1[i])

len(l1)

list(range(len(l1)-1,-1,-1))

l1

for i in range(len(l1)-1,-1,-1):
  print(l1[i])

l2=["abhay","gautam","sunil","singh","pooja","gupta","neha","rajput"]

len(l2)

range(len(l2))

list(range(len(l2)))

for i in range(len(l2)):
  print(l2[i])

for i in range(len(l2)-1,-1,-1):
  print(l2[i])

